#! /usr/bin/env bash
# vim: filetype=sh syntax=sh

if [[ $# -lt 2 ]]
then
  echo "Usage: ${0##*/} <input> <file> [...]"
  exit 1
fi

message=$1

shift

while (($#))
do
  if [[ -d "$1" ]]
  then
    shift
    continue
  elif [[ -f "$1" ]]
  then
    echo -e "$message" >> "$1"
  else
    echo -e "$message" > "$1"
  fi

  shift
done

